<a href="https://colab.research.google.com/github/vitorcapdeville/alura-data-science/blob/main/Semana_6_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Gerar dados aleatórios usando np.random

In [2]:
rng = np.random.default_rng(12345)
size = 100
id = np.arange(size)
idade = rng.integers(low = 18, high = 120, size = size)
sexo = rng.choice(["F", "M"], size = size)
estado_civil = rng.choice(["solteiro", "casado", "divorciado", "viuvo"], size = size)
sinistros = rng.poisson(3, size = size)
premio = np.exp(rng.normal(5, 3, size))

Clientes com mais do que 30 anos.

In [3]:
idade[idade > 30].size

89

In [4]:
id[np.logical_and(premio > 1000, sinistros == 0)]

array([56])

In [5]:
idade

array([ 89,  41,  98,  50,  38,  99,  83,  86, 118,  57, 103,  51,  75,
        79,  39,  37,  41,  86,  80, 114,  90,  43, 111, 114,  92,  86,
        31,  27,  45,  63,  25, 108,  66,  89,  39,  51,  29,  92,  96,
        40,  90,  26,  57,  34,  93,  52,  66,  65,  66,  45,  74, 101,
        68,  37,  20,  31,  26,  27,  30,  79, 100, 105,  84,  79,  51,
       113,  83,  91,  92, 105,  89, 112,  73,  73,  43, 113,  74,  68,
        50,  45,  82,  64,  75,  85, 109,  51,  87, 110,  64,  44,  47,
        52,  82,  44, 103,  54,  24,  18,  20,  82])

In [6]:
categorizacao = np.digitize(idade, bins = [18, 31, 46, 61])
faixas = {
    1: "Faixa etária 18-30",
    2: "Faixa etária 31-45",
    3: "Faixa etária 46-60",
    4: "Faixa etária mais de 60"
}
faixa_etaria = np.vectorize(faixas.get)(categorizacao)

In [7]:
for value, counts in zip(*np.unique(faixa_etaria, return_counts=True)):
  print(f"{value}: {counts}")

Faixa etária 18-30: 11
Faixa etária 31-45: 18
Faixa etária 46-60: 12
Faixa etária mais de 60: 59


In [8]:
values, idx = np.unique(np.sort(estado_civil), return_index = True)
premio_ordenado_por_estado_civil = premio[estado_civil.argsort()]
premio_por_estado_civil = np.split(premio_ordenado_por_estado_civil, idx[1:])

In [9]:
for value, premio_estado in zip(values, premio_por_estado_civil):
    print(f"{value}: R$ {premio_estado.mean():.2f}")

casado: R$ 3519.42
divorciado: R$ 5437.75
solteiro: R$ 2708.31
viuvo: R$ 85131.31


In [10]:
id[premio > premio.mean()]

array([23, 26, 30, 75, 96])